-- PL/SQL DEPARTMENTS 테이블에 전체 내용을 CURSOR 저장하고 FETCH해서 전체정보를 출력하시오
DECLARE
        VDEPARTMENTS DEPARTMENTS%ROWTYPE;
        CURSOR C1 IS SELECT * FROM DEPARTMENTS;
BEGIN
        /*
        OPEN C1;
        LOOP
                FETCH C1 INTO VDEPARTMENTS;
                EXIT WHEN C1%NOTFOUND;
                DBMS_OUTPUT.PUT_LINE(VDEPARTMENTS.DEPARTMENT_ID||' / '||VDEPARTMENTS.DEPARTMENT_NAME);
        END LOOP;
        CLOSE C1;
        */
        FOR VDEPARTMENTS IN C1 LOOP
            DBMS_OUTPUT.PUT_LINE(VDEPARTMENTS.DEPARTMENT_ID||' / '||VDEPARTMENTS.DEPARTMENT_NAME);
        END LOOP;
END;
/