-- 순위 함수 RANK() DENSE_RANK(), ROWNUM
--ROWNUM구하는 순위 (다쓰인다)
DROP TABLE EMP02;
CREATE TABLE EMP02
AS
SELECT * FROM EMPLOYEES WHERE 1=1;
SELECT * FROM EMP02;
SELECT ROWNUM,FIRST_NAME,SALARY FROM EMPLOYEES 
        ORDER BY SALARY DESC;
SELECT ROWNUM,FIRST_NAME,SALARY FROM (SELECT FIRST_NAME,SALARY FROM EMPLOYEES 
        ORDER BY SALARY DESC);
--공동순위를 수하는 방법 RANK( ),DENSE_RANK( )
SELECT RANK() OVER (ORDER BY SALARY DESC) AS RANK,FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DENSE_RANK,FIRST_NAME,SALARY FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT ROWNUM,RANK() OVER (ORDER BY SALARY DESC) AS RANK,
DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DENSE_RANK,FIRST_NAME,SALARY FROM (SELECT FIRST_NAME,SALARY FROM EMPLOYEES 
        ORDER BY SALARY DESC);
        
--중복순위 없애기
SELECT RANK() OVER (ORDER BY SALARY DESC,COMMISSION_PCT DESC) AS RANK,FIRST_NAME,SALARY,COMMISSION_PCT
    FROM EMPLOYEES ORDER BY SALARY DESC;
    
--부서별 순위 구하기
SELECT DEPARTMENT_ID,RANK() OVER (PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC,COMMISSION_PCT DESC) AS RANK,FIRST_NAME,SALARY,COMMISSION_PCT
    FROM EMPLOYEES ORDER BY DEPARTMENT_ID, SALARY DESC,COMMISSION_PCT DESC;
    SELECT DEPARTMENT_ID,RANK() OVER (ORDER BY SALARY DESC,COMMISSION_PCT DESC) AS RANK,FIRST_NAME,SALARY,COMMISSION_PCT
    FROM EMPLOYEES ORDER BY DEPARTMENT_ID, SALARY DESC,COMMISSION_PCT DESC;

--ROWNUM 규칙 중요
--2PAGE
--start := ((num_page_no - 1) * num_page_size) + 1 # 출력 페이지 시작행
--end := (num_page_no * num_page_size) #출력 페이지 마지막 행
SELECT * FROM EMPLOYEES WHERE ROWNUM BETWEEN 11 AND 20;
SELECT ROWNUM, E.* FROM EMPLOYEES E;

--순위구하기(비추천)
SELECT * FROM (SELECT ROWNUM AS RNUM,E.*FROM EMPLOYEES E)
    WHERE RNUM BETWEEN 11 AND 20;
    
--순위구하기 (추천)
SELECT * FROM (SELECT ROWNUM AS RNUM,E.*FROM EMPLOYEES E WHERE ROWNUM<=110)
    WHERE RNUM BETWEEN 80 AND 110;