--EMPLOYEES를 복사
CREATE TABLE EMP03 AS SELECT * FROM EMPLOYEES;

--모든 사원의 부서번호를 30번으로 수정하자
SELECT * FROM EMP03;
UPDATE EMP03 SET DEPARTMENT_ID = 30;
--모든 사원의 급여를 10%인상한다
UPDATE EMP03 SET SALARY = SALARY * 1.1;
--입사일을 오늘로 수정한다
UPDATE EMP03 SET HIRE_DATE = SYSDATE;
ROLLBACK;
--부서번호가 10번인 사원의 부서번호를 30번으로 수정
UPDATE EMP03 SET DEPARTMENT_ID = 30 WHERE DEPARTMENT_ID = 10;
--급여가 3000 이상인 사원만 급여를 10프로 인상
UPDATE EMP03 SET SALARY = SALARY*1.1 WHERE SALARY >= 3000;