--STORED PROCEDURE
--EMPLOYEES 에서 사용자 이름을 패턴으로 검색한 뒤 해당되는 사용자 정보(사원번호,이름,급여)를 보여주시오

CREATE OR REPLACE PROCEDURE EMP_PROC
IS 
    VWORD VARCHAR2(1);
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
    CURSOR CURSOR_NAME(VNAME EMPLOYEES.FIRST_NAME%TYPE)
    IS
    SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE UPPER('%'||VNAME||'%');
BEGIN
    --임의의 문자를 생성시킨다
    VWORD := DBMS_RANDOM.STRING('U',1);
    
    FOR VEMP_ROWTYPE IN CURSOR_NAME(VWORD) LOOP
            DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME|| ' / '||VEMP_ROWTYPE.SALARY);
    END LOOP;
END;
/
SHOW ERROR;

EXECUTE EMP_PROC;

--DATA DICTIONARY
--USER_CONSTARAINTS, USER_INDEXES,USER_TABLES,USER_CONS_COLUMS,USER_VIEWS,USER_SOURCE

SELECT * FROM USER_TABLES;
SELECT * FROM USER_SOURCE;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONS_COLUMNS;
SELECT * FROM USER_IND_COLUMNS;
SELECT * FROM USER_VIEWS;
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_SEQUENCES;

CREATE OR REPLACE PROCEDURE EMP_PROC2(VWORD IN VARCHAR2)
IS 
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE;
    CURSOR CURSOR_NAME(VWORD VARCHAR2)
    IS
    SELECT * FROM EMPLOYEES WHERE UPPER(FIRST_NAME) LIKE UPPER('%'||VWORD||'%');
BEGIN
    --임의의 문자를 생성시킨다
    FOR VEMP_ROWTYPE IN CURSOR_NAME(VWORD) LOOP
            DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME|| ' / '||VEMP_ROWTYPE.SALARY);
    END LOOP;
END;
/
EXeCUTE EMP_PROC2('k');

declare
    
begin
    dbms_output.put_line('hello');
end;
/