--EMPLOYEES를 복사
CREATE TABLE EMP03 AS SELECT * FROM EMPLOYEES;

--모든 사원의 부서번호를 30번으로 수정하자
SELECT * FROM EMP03;
UPDATE EMP03 SET DEPARTMENT_ID = 30;
--모든 사원의 급여를 10%인상한다
UPDATE EMP03 SET SALARY = SALARY * 1.1;
--입사일을 오늘로 수정한다
UPDATE EMP03 SET HIRE_DATE = SYSDATE;
ROLLBACK;
--부서번호가 10번인 사원의 부서번호를 30번으로 수정
UPDATE EMP03 SET DEPARTMENT_ID = 30 WHERE DEPARTMENT_ID = 10;
--급여가 3000 이상인 사원만 급여를 10프로 인상
UPDATE EMP03 SET SALARY = SALARY*1.1 WHERE SALARY >= 3000;
--2007년에 입사한 사원의 입사일을 오늘로 수정한다
update emp03 set hire_date = sysdate where substr(hire_date,1,2) = '07';
--susan의 부서번호는 20번으로, 직급은 fi_mar
update emp03 set department_id = '20' ,job_id = 'FI_MGR' where upper(first_name) = upper('Susan');
--last name이 russell인 사원의 급여를 1700으로 커미션 비율 0.45 증가
update emp03 set salary = 17000,commission_pct = 1.45 * commission_pct where upper(last_name) = upper('Russell');
rollback;
--롤백후 
delete from emp03 where department_id = 30;
--
-- 장표
CREATE TABLE MYCUSTOMER(
    code VARCHAR2(7),
    name VARCHAR2(10) CONSTRAINT MYCUSTOMER_NAME_NN NOT NULL,
    gender CHAR(1) NOT NULL,
    birth VARCHAR2(8)NOT NULL,
    phone VARCHAR2(16),
);

ALTER TABLE MYCUSTOMER ADD CONSTRAINT MYCUSTOMER_code_PK PRIMARY KEY(code);
ALTER TABLE MYCUSTOMER ADD CONSTRAINT MYCUSTOMER_gender_CK CHECK(gender IN('M','W'));
ALTER TABLE MYCUSTOMER ADD CONSTRAINT MYCUSTOMER_PHONE_UK UNIQUE(PHONE);
DESC MYCUSTOMER;

INSERT INTO MYCUSTOMER VALUES ('2017108','박승대','M','19711430','010-2580-9919');
INSERT INTO MYCUSTOMER VALUES ('2019302','전미래','W','19740812','010-8864-0232');
SELECT * FROM MYCUSTOMER;
SELECT * FROM CUSTOMER;
DESC CUSTOMER;

-- 제약조건 검색기능(반드시 알아둘것)
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CUSTOMER';
SELECT * FROM USER_TABLES;
SELECT * FROM user_cons_columns WHERE TABLE_NAME = 'CUSTOMER';
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_EMAIL_UK;
ALTER TABLE CUSTOMER DROP CONSTRAINT CUSTOMER_GENDER_CK;


-- MERGE  MYCUSTOMER - > CUSTOMER 병합을진행하는데 없으면 INSERT, 있으면 UPDATE
MERGE INTO CUSTOMER C
    USING MYCUSTOMER M
    ON (C.CODE = M.CODE)
    WHEN MATCHED THEN
        UPDATE SET C.NAME = M.NAME, C.GENDER = M.GENDER, C.BIRTH = M.BIRTH, C.PONE = M.PHONE 
    WHEN NOT MATCHED THEN
        INSERT (C.CODE,C.NAME,C.GENDER,C.BIRTH, C.PONE) values(M.CODE,M.NAME,M.GENDER,M.BIRTH, M.PHONE);

SELECT * FROM CUSTOMER;
SELECT * FROM MYCUSTOMER;
UPDATE MYCUSTOMER SET NAME = '박승우' WHERE CODE = '2017108';

-----
CREATE TABLE EMP001(
    NO NUMBER(4),
    NAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    MANAGER NUMBER(4),
    HIREDATE DATE NOT NULL,
    SALARY NUMBER(7,2) NOT NULL,
    COMM NUMBER(7,2) DEFAULT 0.0,
    DEPTNO NUMBER(2) NOT NULL
    );
    ALTER TABLE EMP001 ADD CONSTRAINT EMP001_NO_PK PRIMARY KEY(NO);
    ALTER TABLE EMP001 ADD CONSTRAINT EMP001_DEPTNO_UL UNIQUE(DEPTNO);
    -------------
    INSERT INTO EMP001 VALUES (7369,'SMITH','CLEAK',7836,'80/12/17',800,NULL,20);
    INSERT INTO EMP001 VALUES (7499,'ALLEN','SALESMAN',7369,'87/12/20',1600,300,30);
    INSERT INTO EMP001 VALUES (7839,'KING','PRESIDENT',NULL,'81/02/08',5000,NULL,10);
    SELECT * FROM EMP001;
    SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP001';
    -------------
    DROP TABLE DEPT;
    DROP TABLE EMP;
    CREATE TABLE DEPT(
        DEPTNO NUMBER(10),
        DEPTNAME VARCHAR2(10),
        AREANAME VARCHAR2(10)
        );
    ALTER TABLE DEPT ADD CONSTRAINT DEPT_DEPTNO_PK PRIMARY KEY(DEPTNO);
    
    CREATE TABLE EMP(
        EMPNO NUMBER(10),
        EMPNAME VARCHAR2(10),
        JOBID VARCHAR2(10),
        SALARY NUMBER(10),
        DEPTNO NUMBER(10)
        );
    ALTER TABLE EMP  ADD CONSTRAINT EMP_EMPNO_PK PRIMARY KEY(EMPNO);
    ALTER TABLE EMP ADD CONSTRAINT EMP_DEPTNO_FK FOREIGN KEY (DEPTNO) 
    REFERENCES DEPT (DEPTNO);
    
    SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'DEPT';    
    SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMP';
    ---------------------
    DROP TABLE DEPT02;
    DROP TABLE MEMBER;
    CREATE TABLE DEPT02(
    DEPT_NO NUMBER,
    DEPT_NAME VARCHAR2(10),
    LOCATION VARCHAR2(10)
);

ALTER TABLE DEPT02 ADD CONSTRAINT DEPT02_NO_PK PRIMARY KEY(DEPT_NO);

INSERT INTO DEPT02 VALUES(10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT02 VALUES(20,'RESEARCH','DALLAS');
INSERT INTO DEPT02 VALUES(30,'SALES','CHICAGO');
INSERT INTO DEPT02 VALUES(40,'OPERATIONS','BOSTON');

CREATE TABLE MEMBER(
    MEMBER_NO NUMBER,
    MEMBER_NAME VARCHAR(10),
    JOB_ID VARCHAR(10),
    DEPT_NO NUMBER
);

ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_NO_PK PRIMARY KEY(MEMBER_NO);
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_NO_FK FOREIGN KEY(DEPT_NO) REFERENCES DEPT02(DEPT_NO);

INSERT INTO MEMBER VALUES(7499,'ALLEN','SALESMAN',30);
INSERT INTO MEMBER VALUES(7566,'JONES','MANAGER',40);

DELETE FROM MEMBER WHERE DEPT_NO = 40;
DELETE FROM DEPT02 WHERE DEPT_NO = 40;

ALTER TABLE MEMBER DROP CONSTRAINT MEMBER_DEPT_NO_FK;
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_NO_FK FOREIGN KEY(DEPT_NO) REFERENCE DEPT02 (NO)ON DELETE CASCADE;
------------------------------------------------------------------------------
