DECLARE
        TYPE FIRST_NAME_ARR_TYPE IS TABLE OF
                EMPLOYEES.FIRST_NAME%TYPE INDEX BY BINARY_INTEGER;
        TYPE JOB_ID_ARR_TYPE IS TABLE OF
                EMPLOYEES.JOB_ID%TYPE INDEX BY BINARY_INTEGER;
        TYPE EMPLOYEE_ID_ARR_TYPE IS TABLE OF
                EMPLOYEES.EMPLOYEE_ID%TYPE INDEX BY BINARY_INTEGER;        
        
        FIRST_NAME_ARR FIRST_NAME_ARR_TYPE;
        JOB_ID_ARR JOB_ID_ARR_TYPE;
        EMPLOYEE_ID_ARR EMPLOYEE_ID_ARR_TYPE;
        ROW_ARR EMPLOYEES%ROWTYPE;
                
        I BINARY_INTEGER := 0;
        J BINARY_INTEGER;
BEGIN
        FOR ROW_ARR IN (SELECT * FROM EMPLOYEES) LOOP
                I := I +1;
                FIRST_NAME_ARR(I) := ROW_ARR.FIRST_NAME;
                JOB_ID_ARR(I) := ROW_ARR.JOB_ID;
                EMPLOYEE_ID_ARR(I) := ROW_ARR.EMPLOYEE_ID;            
        END LOOP;
        --FOR J IN 1..I LOOP
               -- DBMS_OUTPU
        --END LOOP;
END;
/