--MVC 모델방식 적용
DROP TABLE STUDENTS;
CREATE TABLE STUDENTS(
    ID NUMBER(6),
    NAME VARCHAR2(10),
    KOR NUMBER(3),
    ENG NUMBER(3),
    MATH NUMBER(3),
    SUM NUMBER(3),
    AVG NUMBER(3),
    PASS VARCHAR(15) default '미정'
);
ALTER TABLE STUDENTS ADD CONSTRAINT STUDENT_ID_PK PRIMARY KEY(ID);


CREATE SEQUENCE STUDENTS_ID_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM STUDENTS;

--update 시 합, 평균이 같이 변하는 트리거 생성
CREATE OR REPLACE TRIGGER STU_TRIGGER_UPDATE
BEFORE UPDATE ON STUDENTS
FOR EACH ROW
BEGIN
    :NEW.SUM := :NEW.KOR + :NEW.ENG + :NEW.MATH;
    :NEW.AVG := ROUND((:NEW.KOR + :NEW.ENG + :NEW.MATH) / 3, 1);
END;
/

CREATE OR REPLACE PROCEDURE STUDENTS_PROCEDURE(
    VID IN STUDENTS.ID%TYPE,
    VMESSAGE OUT VARCHAR2)
IS
    VSTUDENTS_RT STUDENTS%ROWTYPE; 
    VSUM NUMBER(3);
BEGIN
    SELECT SUM INTO VSUM FROM STUDENTS WHERE ID = VID;
    IF VSUM >= 180 THEN
        UPDATE STUDENTS 
        SET PASS = '합격' 
        WHERE ID = VID;
    ELSE
        UPDATE STUDENTS 
        SET PASS = '불합격' 
        WHERE ID = VID;
    END IF;
    COMMIT;
    SELECT * INTO VSTUDENTS_RT FROM STUDENTS WHERE ID = VID; 
    VMESSAGE := VSTUDENTS_RT.ID || ' 번호의 학생은 시험에서 ' || VSTUDENTS_RT.PASS || '입니다'; 
    DBMS_OUTPUT.PUT_LINE(VMESSAGE); 
END;
/
VARIABLE MESSAGE VARCHAR2(200);
EXECUTE STUDENTS_PROCEDURE(61,:MESSAGE);

SELECT * FROM STUDENTS;
--INSERT INTO STUDENTS(ID,NAME,KOR,ENG,MATH) VALUES((SELECT NVL(MAX(ID),0)+1 FROM STUDENTS),DBMS_RANDOM.STRING('U',5),
--ROUND(DBMS_RANDOM.VALUE(50,100)),ROUND(DBMS_RANDOM.VALUE(50,100)),ROUND(DBMS_RANDOM.VALUE(50,100)));
--INSERT INTO STUDENTS(ID,NAME,KOR,ENG,MATH) VALUES(1,'영구',55,77,88);
--UPDATE STUDENTS SET ID = 2, NAME = 'NAME',KOR =1,ENG=3,MATH=3  WHERE ID = 8;

truncate table students;
--=======================================
