drop table Menutable;
DROP SEQUENCE  MENUTABLE_B_NO_SEQ;
CREATE TABLE MENUTABLE(
    B_NO NUMBER(3),
    NAME VARCHAR2(20) NOT NULL,
    PRICE NUMBER(5) NOT NULL,
    amount number(5) not null
);
ALTER TABLE MENUTABLE ADD CONSTRAINT MENUTABLE_B_NO_PK PRIMARY KEY(B_NO);
ALTER TABLE MENUTABLE ADD CONSTRAINT MENUTABLE_NAME_UK UNIQUE(NAME);

CREATE SEQUENCE MENUTABLE_B_NO_SEQ
START WITH 1
INCREMENT BY 1;
------------------------------------------------------------------------------
drop table CUSTOMER;
DROP SEQUENCE  CUSTOMER_C_NO_SEQ;
CREATE TABLE CUSTOMER(
    C_NO NUMBER(3),
    NAME VARCHAR2(20) NOT NULL,
    B_NO NUMBER(3),
    AMOUNT NUMBER(2)
);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_C_NO_PK PRIMARY KEY(C_NO);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_B_NO_FK FOREIGN KEY(B_NO)
    REFERENCES MENUTABLE(B_NO) ON DELETE SET NULL;

CREATE SEQUENCE CUSTOMER_C_NO_SEQ
START WITH 1
INCREMENT BY 1;
-----------------------------------------------------
DROP TABLE SHOP;
DROP SEQUENCE  SHOP_NO_SEQ;
CREATE TABLE SHOP(
    NO NUMBER(3),
    B_NO NUMBER(3),
    INCOME NUMBER(7)
);
ALTER TABLE SHOP ADD CONSTRAINT SHOP_NO_PK PRIMARY KEY(NO);
ALTER TABLE SHOP ADD CONSTRAINT SHOP_B_NO_FK FOREIGN KEY(B_NO)
    REFERENCES MENUTABLE(B_NO) ON DELETE SET NULL;
    
 CREATE SEQUENCE SHOP_NO_SEQ
START WITH 1
INCREMENT BY 1;
--------------------------------------------
create procedure (